Implement PLONK Verifier Steps 7 to 9
NethermindEth/verify-everything pull request #5
Opened 2024-08-14 02:08 UTC by twliu-dorian

This pull request implements steps 7 to 9 of the PLONK verifier. These steps enhance the verification process by computing essential polynomials and commitments necessary for accurate and efficient proof verification.

## Changes Made

- **Step 7: Public Input Polynomial Evaluation**
  - Implemented the computation of the public input polynomial \( PI(z) \) as a weighted sum of Lagrange polynomials, ensuring accurate evaluation of public inputs.

- **Step 8: Compute Constant Term \( r0 \)**
  - Calculated the constant term \( r0 \) of the polynomial \( r(X) \) by evaluating key components such as Lagrange polynomial \( L1(z) \) and verifier challenges \(alpha, beta, gamma\).

- **Step 9: First Part of Batched Polynomial Commitment**
  - Developed the first part of the batched polynomial commitment by integrating \( r0 \) and other polynomial terms, optimizing the verifier's scalar multiplication operations.

## Testing and Validation

- Added unit tests for each new component to ensure correctness and robustness.
- Validated against known test vectors to verify implementation accuracy.

## Next Steps

- Continue with subsequent steps in the PLONK verification process.
- Optimize performance based on profiling results.

2024-08-19 18:14 UTC, danielntmd requested changes

2024-08-19 18:14 UTC, danielntmd commented on plonk-verifier/src/math/fast_mod_tests.cairo
>  #[test]
Lines 205-208: Let's implement an equals comparison operator so we can reduce 4 asserts to 1, and let's do this for the other structs you have made in lines 222-225 and 228-231 respectively

2024-08-19 18:14 UTC, danielntmd commented on plonk-verifier/src/fields/tests/fq.cairo
>  fn test_main() {
Lines 48-49: What is this test_main asserting? Can we either remove or make it clear with the variables?

2024-08-19 18:14 UTC, danielntmd commented on plonk-verifier/src/fields/tests/fq.cairo
>  }
Clean "//"

2024-08-19 18:14 UTC, danielntmd commented on plonk-verifier/src/fields/tests/fq12.cairo
Lines 0- 80 (minor clean): We could turn these function calls instead into const vars or just place them under the mul_assoc function since we only use these functions for a single test

2024-08-21 14:47 UTC, twliu-dorian commented on plonk-verifier/src/fields/tests/fq.cairo
>  fn test_main() {
I will remove it in the next commit

2024-08-21 14:48 UTC, twliu-dorian commented on plonk-verifier/src/fields/tests/fq.cairo
>  }
I will clean up all the "//"

2024-08-21 14:49 UTC, twliu-dorian commented on plonk-verifier/src/fields/tests/fq12.cairo
I will place them under the mul_assoc function.

2024-08-21 18:14 UTC, twliu-dorian commented on plonk-verifier/src/math/fast_mod_tests.cairo
>  #[test]
Reduced 4 assertions to one by comparing the equivalence of the entire struct.

2024-08-27 05:23 UTC, danielntmd commented
merged

2024-08-27 05:23 UTC, closed without merging